app:
  messaging:
    input-topic: ${APP_MESSAGING_INPUT_TOPIC:stochastic-input}
  outbox:
    enabled: ${APP_OUTBOX_ENABLED:true}
    interval: ${APP_OUTBOX_INTERVAL:5000}

server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:stochastic_labs_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
      acks: all